//
// Generated file, do not edit! Created by opp_msgtool 6.0 from gtc_header.msg.
//

#ifndef __GTC_HEADER_M_H
#define __GTC_HEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class gtc_header;
/**
 * Class generated from <tt>gtc_header.msg:17</tt> by opp_msgtool.
 * <pre>
 * packet gtc_header extends cPacket
 * {
 *     bool Downlink = false;
 *     bool Uplink = false;
 *     bool Ext_pon = false;
 *     bool Int_pon = false;
 * 
 *     //uint32_t PSync;					// 4 Bytes
 *     //uint32_t Ident;					// 4 Bytes
 *     //double PLOAMd;					// 13 Bytes
 *     //uint8_t BIP;						// 1 Byte
 *     //uint32_t Plend;					// 4 Bytes (repeated twice)
 *     //double us_bw_map_size;			// N*8 Bytes
 * 
 *     double Olt_onu_rtt[];
 *     double Onu_start_time_TC1[];
 *     double Onu_grant_TC1[];
 *     double Onu_start_time_TC2[];
 *     double Onu_grant_TC2[];
 *     double Onu_start_time_TC3[];
 *     double Onu_grant_TC3[];
 * 
 *     double Mfu_sfu_rtt[];
 *     double Sfu_start_time_TC1[];
 *     double Sfu_grant_TC1[];
 *     double Sfu_start_time_TC2[];
 *     double Sfu_grant_TC2[];
 *     double Sfu_start_time_TC3[];
 *     double Sfu_grant_TC3[];
 * 
 *     //uint8_t AllocID;					// 14 bits
 *     //uint8_t Flags;					// 2 bits
 *     //uint8_t StartTime;				// 16 bits
 *     //uint8_t GrantSize;				// 16 bits
 *     //uint8_t FWI;						// 1 bit
 *     //uint8_t BurstProfile;				// 2 bits
 *     //uint8_t HEC;						// 13 bits
 * 
 *     int OnuID;
 *     int SfuID;
 *     int MfuID;
 *     double BufferOccupancyTC1 = 0.0;				// 24 bits
 *     double BufferOccupancyTC2 = 0.0;				// 24 bits
 *     double BufferOccupancyTC3 = 0.0;				// 24 bits
 * 
 *     long SeqID;
 * 
 *     // int flags;						// 8 bits
 *     // int allocID;						// 12 bits
 *     // double timestamp;				// 20 bits - Local time value used for ranging and drift correction
 * }
 * </pre>
 */
class gtc_header : public ::omnetpp::cPacket
{
  protected:
    bool Downlink = false;
    bool Uplink = false;
    bool Ext_pon = false;
    bool Int_pon = false;
    double *Olt_onu_rtt = nullptr;
    size_t Olt_onu_rtt_arraysize = 0;
    double *Onu_start_time_TC1 = nullptr;
    size_t Onu_start_time_TC1_arraysize = 0;
    double *Onu_grant_TC1 = nullptr;
    size_t Onu_grant_TC1_arraysize = 0;
    double *Onu_start_time_TC2 = nullptr;
    size_t Onu_start_time_TC2_arraysize = 0;
    double *Onu_grant_TC2 = nullptr;
    size_t Onu_grant_TC2_arraysize = 0;
    double *Onu_start_time_TC3 = nullptr;
    size_t Onu_start_time_TC3_arraysize = 0;
    double *Onu_grant_TC3 = nullptr;
    size_t Onu_grant_TC3_arraysize = 0;
    double *Mfu_sfu_rtt = nullptr;
    size_t Mfu_sfu_rtt_arraysize = 0;
    double *Sfu_start_time_TC1 = nullptr;
    size_t Sfu_start_time_TC1_arraysize = 0;
    double *Sfu_grant_TC1 = nullptr;
    size_t Sfu_grant_TC1_arraysize = 0;
    double *Sfu_start_time_TC2 = nullptr;
    size_t Sfu_start_time_TC2_arraysize = 0;
    double *Sfu_grant_TC2 = nullptr;
    size_t Sfu_grant_TC2_arraysize = 0;
    double *Sfu_start_time_TC3 = nullptr;
    size_t Sfu_start_time_TC3_arraysize = 0;
    double *Sfu_grant_TC3 = nullptr;
    size_t Sfu_grant_TC3_arraysize = 0;
    int OnuID = 0;
    int SfuID = 0;
    int MfuID = 0;
    double BufferOccupancyTC1 = 0.0;
    double BufferOccupancyTC2 = 0.0;
    double BufferOccupancyTC3 = 0.0;
    long SeqID = 0;

  private:
    void copy(const gtc_header& other);

  protected:
    bool operator==(const gtc_header&) = delete;

  public:
    gtc_header(const char *name=nullptr, short kind=0);
    gtc_header(const gtc_header& other);
    virtual ~gtc_header();
    gtc_header& operator=(const gtc_header& other);
    virtual gtc_header *dup() const override {return new gtc_header(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getDownlink() const;
    virtual void setDownlink(bool Downlink);

    virtual bool getUplink() const;
    virtual void setUplink(bool Uplink);

    virtual bool getExt_pon() const;
    virtual void setExt_pon(bool Ext_pon);

    virtual bool getInt_pon() const;
    virtual void setInt_pon(bool Int_pon);

    virtual void setOlt_onu_rttArraySize(size_t size);
    virtual size_t getOlt_onu_rttArraySize() const;
    virtual double getOlt_onu_rtt(size_t k) const;
    virtual void setOlt_onu_rtt(size_t k, double Olt_onu_rtt);
    virtual void insertOlt_onu_rtt(size_t k, double Olt_onu_rtt);
    [[deprecated]] void insertOlt_onu_rtt(double Olt_onu_rtt) {appendOlt_onu_rtt(Olt_onu_rtt);}
    virtual void appendOlt_onu_rtt(double Olt_onu_rtt);
    virtual void eraseOlt_onu_rtt(size_t k);

    virtual void setOnu_start_time_TC1ArraySize(size_t size);
    virtual size_t getOnu_start_time_TC1ArraySize() const;
    virtual double getOnu_start_time_TC1(size_t k) const;
    virtual void setOnu_start_time_TC1(size_t k, double Onu_start_time_TC1);
    virtual void insertOnu_start_time_TC1(size_t k, double Onu_start_time_TC1);
    [[deprecated]] void insertOnu_start_time_TC1(double Onu_start_time_TC1) {appendOnu_start_time_TC1(Onu_start_time_TC1);}
    virtual void appendOnu_start_time_TC1(double Onu_start_time_TC1);
    virtual void eraseOnu_start_time_TC1(size_t k);

    virtual void setOnu_grant_TC1ArraySize(size_t size);
    virtual size_t getOnu_grant_TC1ArraySize() const;
    virtual double getOnu_grant_TC1(size_t k) const;
    virtual void setOnu_grant_TC1(size_t k, double Onu_grant_TC1);
    virtual void insertOnu_grant_TC1(size_t k, double Onu_grant_TC1);
    [[deprecated]] void insertOnu_grant_TC1(double Onu_grant_TC1) {appendOnu_grant_TC1(Onu_grant_TC1);}
    virtual void appendOnu_grant_TC1(double Onu_grant_TC1);
    virtual void eraseOnu_grant_TC1(size_t k);

    virtual void setOnu_start_time_TC2ArraySize(size_t size);
    virtual size_t getOnu_start_time_TC2ArraySize() const;
    virtual double getOnu_start_time_TC2(size_t k) const;
    virtual void setOnu_start_time_TC2(size_t k, double Onu_start_time_TC2);
    virtual void insertOnu_start_time_TC2(size_t k, double Onu_start_time_TC2);
    [[deprecated]] void insertOnu_start_time_TC2(double Onu_start_time_TC2) {appendOnu_start_time_TC2(Onu_start_time_TC2);}
    virtual void appendOnu_start_time_TC2(double Onu_start_time_TC2);
    virtual void eraseOnu_start_time_TC2(size_t k);

    virtual void setOnu_grant_TC2ArraySize(size_t size);
    virtual size_t getOnu_grant_TC2ArraySize() const;
    virtual double getOnu_grant_TC2(size_t k) const;
    virtual void setOnu_grant_TC2(size_t k, double Onu_grant_TC2);
    virtual void insertOnu_grant_TC2(size_t k, double Onu_grant_TC2);
    [[deprecated]] void insertOnu_grant_TC2(double Onu_grant_TC2) {appendOnu_grant_TC2(Onu_grant_TC2);}
    virtual void appendOnu_grant_TC2(double Onu_grant_TC2);
    virtual void eraseOnu_grant_TC2(size_t k);

    virtual void setOnu_start_time_TC3ArraySize(size_t size);
    virtual size_t getOnu_start_time_TC3ArraySize() const;
    virtual double getOnu_start_time_TC3(size_t k) const;
    virtual void setOnu_start_time_TC3(size_t k, double Onu_start_time_TC3);
    virtual void insertOnu_start_time_TC3(size_t k, double Onu_start_time_TC3);
    [[deprecated]] void insertOnu_start_time_TC3(double Onu_start_time_TC3) {appendOnu_start_time_TC3(Onu_start_time_TC3);}
    virtual void appendOnu_start_time_TC3(double Onu_start_time_TC3);
    virtual void eraseOnu_start_time_TC3(size_t k);

    virtual void setOnu_grant_TC3ArraySize(size_t size);
    virtual size_t getOnu_grant_TC3ArraySize() const;
    virtual double getOnu_grant_TC3(size_t k) const;
    virtual void setOnu_grant_TC3(size_t k, double Onu_grant_TC3);
    virtual void insertOnu_grant_TC3(size_t k, double Onu_grant_TC3);
    [[deprecated]] void insertOnu_grant_TC3(double Onu_grant_TC3) {appendOnu_grant_TC3(Onu_grant_TC3);}
    virtual void appendOnu_grant_TC3(double Onu_grant_TC3);
    virtual void eraseOnu_grant_TC3(size_t k);

    virtual void setMfu_sfu_rttArraySize(size_t size);
    virtual size_t getMfu_sfu_rttArraySize() const;
    virtual double getMfu_sfu_rtt(size_t k) const;
    virtual void setMfu_sfu_rtt(size_t k, double Mfu_sfu_rtt);
    virtual void insertMfu_sfu_rtt(size_t k, double Mfu_sfu_rtt);
    [[deprecated]] void insertMfu_sfu_rtt(double Mfu_sfu_rtt) {appendMfu_sfu_rtt(Mfu_sfu_rtt);}
    virtual void appendMfu_sfu_rtt(double Mfu_sfu_rtt);
    virtual void eraseMfu_sfu_rtt(size_t k);

    virtual void setSfu_start_time_TC1ArraySize(size_t size);
    virtual size_t getSfu_start_time_TC1ArraySize() const;
    virtual double getSfu_start_time_TC1(size_t k) const;
    virtual void setSfu_start_time_TC1(size_t k, double Sfu_start_time_TC1);
    virtual void insertSfu_start_time_TC1(size_t k, double Sfu_start_time_TC1);
    [[deprecated]] void insertSfu_start_time_TC1(double Sfu_start_time_TC1) {appendSfu_start_time_TC1(Sfu_start_time_TC1);}
    virtual void appendSfu_start_time_TC1(double Sfu_start_time_TC1);
    virtual void eraseSfu_start_time_TC1(size_t k);

    virtual void setSfu_grant_TC1ArraySize(size_t size);
    virtual size_t getSfu_grant_TC1ArraySize() const;
    virtual double getSfu_grant_TC1(size_t k) const;
    virtual void setSfu_grant_TC1(size_t k, double Sfu_grant_TC1);
    virtual void insertSfu_grant_TC1(size_t k, double Sfu_grant_TC1);
    [[deprecated]] void insertSfu_grant_TC1(double Sfu_grant_TC1) {appendSfu_grant_TC1(Sfu_grant_TC1);}
    virtual void appendSfu_grant_TC1(double Sfu_grant_TC1);
    virtual void eraseSfu_grant_TC1(size_t k);

    virtual void setSfu_start_time_TC2ArraySize(size_t size);
    virtual size_t getSfu_start_time_TC2ArraySize() const;
    virtual double getSfu_start_time_TC2(size_t k) const;
    virtual void setSfu_start_time_TC2(size_t k, double Sfu_start_time_TC2);
    virtual void insertSfu_start_time_TC2(size_t k, double Sfu_start_time_TC2);
    [[deprecated]] void insertSfu_start_time_TC2(double Sfu_start_time_TC2) {appendSfu_start_time_TC2(Sfu_start_time_TC2);}
    virtual void appendSfu_start_time_TC2(double Sfu_start_time_TC2);
    virtual void eraseSfu_start_time_TC2(size_t k);

    virtual void setSfu_grant_TC2ArraySize(size_t size);
    virtual size_t getSfu_grant_TC2ArraySize() const;
    virtual double getSfu_grant_TC2(size_t k) const;
    virtual void setSfu_grant_TC2(size_t k, double Sfu_grant_TC2);
    virtual void insertSfu_grant_TC2(size_t k, double Sfu_grant_TC2);
    [[deprecated]] void insertSfu_grant_TC2(double Sfu_grant_TC2) {appendSfu_grant_TC2(Sfu_grant_TC2);}
    virtual void appendSfu_grant_TC2(double Sfu_grant_TC2);
    virtual void eraseSfu_grant_TC2(size_t k);

    virtual void setSfu_start_time_TC3ArraySize(size_t size);
    virtual size_t getSfu_start_time_TC3ArraySize() const;
    virtual double getSfu_start_time_TC3(size_t k) const;
    virtual void setSfu_start_time_TC3(size_t k, double Sfu_start_time_TC3);
    virtual void insertSfu_start_time_TC3(size_t k, double Sfu_start_time_TC3);
    [[deprecated]] void insertSfu_start_time_TC3(double Sfu_start_time_TC3) {appendSfu_start_time_TC3(Sfu_start_time_TC3);}
    virtual void appendSfu_start_time_TC3(double Sfu_start_time_TC3);
    virtual void eraseSfu_start_time_TC3(size_t k);

    virtual void setSfu_grant_TC3ArraySize(size_t size);
    virtual size_t getSfu_grant_TC3ArraySize() const;
    virtual double getSfu_grant_TC3(size_t k) const;
    virtual void setSfu_grant_TC3(size_t k, double Sfu_grant_TC3);
    virtual void insertSfu_grant_TC3(size_t k, double Sfu_grant_TC3);
    [[deprecated]] void insertSfu_grant_TC3(double Sfu_grant_TC3) {appendSfu_grant_TC3(Sfu_grant_TC3);}
    virtual void appendSfu_grant_TC3(double Sfu_grant_TC3);
    virtual void eraseSfu_grant_TC3(size_t k);

    virtual int getOnuID() const;
    virtual void setOnuID(int OnuID);

    virtual int getSfuID() const;
    virtual void setSfuID(int SfuID);

    virtual int getMfuID() const;
    virtual void setMfuID(int MfuID);

    virtual double getBufferOccupancyTC1() const;
    virtual void setBufferOccupancyTC1(double BufferOccupancyTC1);

    virtual double getBufferOccupancyTC2() const;
    virtual void setBufferOccupancyTC2(double BufferOccupancyTC2);

    virtual double getBufferOccupancyTC3() const;
    virtual void setBufferOccupancyTC3(double BufferOccupancyTC3);

    virtual long getSeqID() const;
    virtual void setSeqID(long SeqID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const gtc_header& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, gtc_header& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline gtc_header *fromAnyPtr(any_ptr ptr) { return check_and_cast<gtc_header*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __GTC_HEADER_M_H

